title: Homelab

background:
  image: /images/moon-mountain.png
  blur: sm
  brightness: 50

theme: dark
color: gray

statusStyle: dot
useEqualHeightCards: true
headerStyle: clean
hideVersion: true
target: _blank

layout:
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Storage:
    style: row
    columns: 3
